Matrix Multiplication

Jeeva, a mathematical expert, is looking for an expert in programming who can assist him in creating a Python program for Matrix Multiplication.

His program has specific requirements.

The matrices have to be saved inside a dictionary.
The keys allowed in the dictionary are [matrix 1, matrix 2, result matrix]
The values for the elements in the rows of the matrix have to be saved in the form of a list of lists [[row1][row2]].
You must have functions for collecting the matrix and store in the dictionary.
Another function to Process the matrix and store it in the dictionary. 
Another function to Display the result in a file, properly formatted.
Menu option to show enter matrix 1, matrix 2, calculate, export to file. If the matrix has been entered, then it should take confirmation from the user before taking the input for matrix 1 or 2 again.

In [1]:
import numpy as np
Matrix1=[]
def add_matrix1():
    global r1
    global c1
    r1=int(input("Enter no of rows:"))
    c1=int(input("Enter no of columns:"))
    for i in range(r1):
        a=[]
        for j in range(c1):
            b=int(input("Enter a number:"))
            a.append(b)
        Matrix1.append(a)
    print("First matrix:\n",np.matrix(Matrix1))




In [2]:
Matrix2=[]
def add_matrix2():
    global r2
    global c2
    r2=int(input("Enter no of rows:"))
    c2=int(input("Enter no of columns:"))
    for i in range(r2):
        x=[]
        for j in range(c2):
            z=int(input("Enter a number:"))
            x.append(z)
        Matrix2.append(x)
    print("Second matrix:\n",np.matrix(Matrix2))




In [3]:
prod_matrix=[]
def product_matrix():
    if r1==c2:

        p=(np.matrix(Matrix1)*np.matrix(Matrix2))#matrix format
        prod_matrix.append(p)
        print(prod_matrix)
    else:
        print("not possible")
    dict={"Matrix 1":Matrix1,"Matrix 2":Matrix2,"Product":prod_matrix}
    print(dict)




In [4]:
def exportFile():
    file=open("matrix.txt","a+")
    file.write("\n"+str(dict))
    file.close()

In [ ]:

while True:

    print("enter your choice")
    print("1. add matrix1")
    print("2.add matrix2")
    print("3.calculate")
    print("4.export to file")   

    choice=input("enter your choice")

    if choice=="1":
        add_matrix1()
    elif choice=="2":
        add_matrix2()
    elif choice=="3":
        product_matrix()
    elif choice=="4":
        exportFile()
    else:
        exit()
    
        
        



enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
First matrix:
 [[2 4 7]
 [8 9 6]
 [1 2 4]]
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
Second matrix:
 [[2 4 9]
 [6 2 7]
 [5 2 9]]
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
[matrix([[ 63,  30, 109],
        [100,  62, 189],
        [ 34,  16,  59]])]
{'Matrix 1': [[2, 4, 7], [8, 9, 6], [1, 2, 4]], 'Matrix 2': [[2, 4, 9], [6, 2, 7], [5, 2, 9]], 'Product': [matrix([[ 63,  30, 109],
        [100,  62, 189],
        [ 34,  16,  59]])]}
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file
enter your choice
1. add matrix1
2.add matrix2
3.calculate
4.export to file


: 